Add support for /proc/<pid>/ns
eminence/procfs pull request #135
Opened 2021-07-09 22:02 UTC by Furisto

2021-07-10 16:48 UTC, eminence requested changes
Thanks for the PR!

The namespaces manual page says this:

> If two processes are in the same namespace, then the device IDs and inode numbers of their /proc/[pid]/ns/xxx symbolic links will be the same; an application can check this using the stat.st_dev and stat.st_ino fields returned by stat(2).  

Do you think this means we should store both `st_dev` and `st_ino` in the `Namespace` struct?

2021-07-10 16:48 UTC, eminence commented on src/process/namespaces.rs
> +    identifier: u64,
These 3 fields should be `pub`, right?

2021-07-10 19:45 UTC, Furisto commented on src/process/namespaces.rs
> +    identifier: u64,
...yes, of course! Fixed it.

2021-07-10 19:49 UTC, Furisto commented
@eminence 
You bring up an interesting point. I had only seen the inode number used to compare namespaces and tools like [lsns](https://github.com/karelzak/util-linux/blob/c2ca2837a27a3f1344904037ea691bfdbb288f02/sys-utils/lsns.c#L104-L118) do not even offer an option to display the device id for a namespace. It [seems](https://lore.kernel.org/lkml/87poky5ca9.fsf@xmission.com/) that the device id is currently not used in this capacity but _could_ be used that way in the future. I am happy to do it either way.

> Like all fstat inode comparisons to be fully accurate you need to
> compare both the st_ino and st_dev.  I reserve the right for st_dev to
> be significant when comparing namespaces.  Otherwise I might have to
> create a namespace of namespaces someday and that is ugly.

2021-07-11 09:15 UTC, Furisto commented
Added the device id and also made namespaces comparable.

2021-07-17 18:40 UTC, Furisto commented
@eminence PTAL

2021-07-20 01:05 UTC, eminence approved these changes
LGTM, thanks!

2021-07-20 01:05 UTC, eminence commented on src/process/namespaces.rs
> +impl Eq for Namespace {}
I think this can replaced by adding `Eq` to the list of automatic derives?  

A super minor thing, though

2021-07-20 01:14 UTC, merged